### ISSUE TITLE
KeyError('avatar')

### ISSUE THREAD

**Issue by RealGatt** [TeKrop/overfast-api#299]
Loading any player page `/players/Calamity-31170/summary` throws the following error in logs.

```
2025-09-25 10:51:02.281 | CRITICAL | app.helpers - Internal server error for URL https://overwatch.blizzard.com/en-us/career/d15fa08bbe788fb4a4a326a1d301%7Ca600f403b6ccb654a0a0b7e61a3a957d/ : KeyError('avatar')
['  File "/code/.venv/bin/fastapi", line 10, in <module>\n    sys.exit(main())\n', '  File "/code/.venv/lib/python3.13/site-packages/fastapi/cli.py", line 13, in main\n    cli_main()\n', '  File "/code/.venv/lib/python3.13/site-packages/fastapi_cli/cli.py", line 374, in main\n    app()\n', '  File "/code/.venv/lib/python3.13/site-packages/typer/main.py", line 313, in __call__\n    return get_command(self)(*args, **kwargs)\n', '  File "/code/.venv/lib/python3.13/site-packages/click/core.py", line 1442, in __call__\n    return self.main(*args, **kwargs)\n', '  File "/code/.venv/lib/python3.13/site-packages/typer/core.py", line 765, in main\n    return _main(\n', '  File "/code/.venv/lib/python3.13/site-packages/typer/core.py", line 193, in _main\n    rv = self.invoke(ctx)\n', '  File "/code/.venv/lib/python3.13/site-packages/click/core.py", line 1830, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n', '  File "/code/.venv/lib/python3.13/site-packages/click/core.py", line 1226, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n', '  File "/code/.venv/lib/python3.13/site-packages/click/core.py", line 794, in invoke\n    return callback(*args, **kwargs)\n', '  File "/code/.venv/lib/python3.13/site-packages/typer/main.py", line 690, in wrapper\n    return callback(**use_params)\n', '  File "/code/.venv/lib/python3.13/site-packages/fastapi_cli/cli.py", line 359, in run\n    _run(\n', '  File "/code/.venv/lib/python3.13/site-packages/fastapi_cli/cli.py", line 173, in _run\n    uvicorn.run(\n', '  File "/code/.venv/lib/python3.13/site-packages/uvicorn/main.py", line 580, in run\n    server.run()\n', '  File "/code/.venv/lib/python3.13/site-packages/uvicorn/server.py", line 67, in run\n    return asyncio.run(self.serve(sockets=sockets))\n', '  File "/usr/local/lib/python3.13/asyncio/runners.py", line 195, in run\n    return runner.run(main)\n', '  File "/usr/local/lib/python3.13/asyncio/runners.py", line 118, in run\n    return self._loop.run_until_complete(task)\n', '  File "/code/.venv/lib/python3.13/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi\n    result = await app(  # type: ignore[func-returns-value]\n', '  File "/code/.venv/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__\n    return await self.app(scope, receive, send)\n', '  File "/code/.venv/lib/python3.13/site-packages/fastapi/applications.py", line 1082, in __call__\n    await super().__call__(scope, receive, send)\n', '  File "/code/.venv/lib/python3.13/site-packages/starlette/applications.py", line 113, in __call__\n    await self.middleware_stack(scope, receive, send)\n', '  File "/code/.venv/lib/python3.13/site-packages/starlette/middleware/errors.py", line 164, in __call__\n    await self.app(scope, receive, _send)\n', '  File "/code/.venv/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n', '  File "/code/.venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app\n    await app(scope, receive, sender)\n', '  File "/code/.venv/lib/python3.13/site-packages/starlette/routing.py", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n', '  File "/code/.venv/lib/python3.13/site-packages/starlette/routing.py", line 736, in app\n    await route.handle(scope, receive, send)\n', '  File "/code/.venv/lib/python3.13/site-packages/starlette/routing.py", line 290, in handle\n    await self.app(scope, receive, send)\n', '  File "/code/.venv/lib/python3.13/site-packages/starlette/routing.py", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n', '  File "/code/.venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app\n    await app(scope, receive, sender)\n', '  File "/code/.venv/lib/python3.13/site-packages/starlette/routing.py", line 75, in app\n    response = await f(request)\n', '  File "/code/.venv/lib/python3.13/site-packages/fastapi/routing.py", line 308, in app\n    raw_response = await run_endpoint_function(\n', '  File "/code/.venv/lib/python3.13/site-packages/fastapi/routing.py", line 219, in run_endpoint_function\n    return await dependant.call(**values)\n', '  File "/code/app/players/router.py", line 156, in get_player_summary\n    return await GetPlayerCareerController(request, response).process_request(\n', '  File "/code/app/controllers.py", line 68, in process_request\n    raise overfast_internal_error(parser.blizzard_url, error) from error\n', '  File "/code/app/helpers.py", line 72, in overfast_internal_error\n    traceback.format_stack(),\n']
2025-09-25 10:51:02.282 | ERROR    | app.helpers - * **URL** : https://overwatch.blizzard.com/en-us/career/d15fa08bbe788fb4a4a326a1d301%7Ca600f403b6ccb654a0a0b7e61a3a957d/
* **Error type** : ParserParsingError
* **Message** : KeyError('avatar')
```

I've confirmed it on two separate installs (my existing and a fresh)

**Comment by TeKrop** [comment]
Hello,

I fixed an issue that seem related last week, did you update your instance with the last API version ?
On my instance, it seems I can load this profile without error.

**Comment by TeKrop** [comment]
I see you seem to be using the last version of the API, I think you need to clear your Valkey cache 🤔 
Either by restarting the container or manually clearing the cache.
Let me know if it works for you 👍

**Comment by TeKrop** [comment]
Hello @RealGatt ,

Did my last suggestion solved your issue ?

**Comment by RealGatt** [comment]
Hi @TeKrop, sorry - I missed the notification!

Sadly still happening... I just pulled recent changes and ran `make clean`, then `make up`.

I also ran `docker exec overfast-api-valkey-1 valkey-cli FLUSHALL` (returning `OK)

**Comment by RealGatt** [comment]
This is the block for the player, returned by that endpoint on my both my local machine and the server running Overfast

Looks like I'm getting "portrait" where I am - for reference, both myself and the server are located in Australia. It could be localisation?

```
  {
    "battleTag": "Calamity#31170",
    "frame": "0x0250000000000919",
    "isPublic": true,
    "lastUpdated": 1745643657,
    "namecard": "0x02500000000068FC",
    "portrait": "0x025000000000114E",
    "title": "0x02500000000055D4",
    "url": "d15fa08bbe788fb4a4a326a1d301%7Ca600f403b6ccb654a0a0b7e61a3a957d"
  },
```

**Comment by TeKrop** [comment]
Oooh could be, not the first time I'm seeing this... 🫠 I'll make a fix accordingly to support both structures 👍 Should be done in a few days

**Comment by TeKrop** [comment]
@RealGatt Do you think you can use the old version of the project in the meantime ? This one was before the changes I made and it should work for you : https://github.com/TeKrop/overfast-api/releases/tag/v3.21.1

**Comment by TeKrop** [comment]
I just released https://github.com/TeKrop/overfast-api/releases/tag/v3.23.1, let me know if it fixes your issue 👍 The only downside : 
- You'll never have namecards, as references doesn't exist anymore
- `avatar` and `title` may be available in player specific endpoint, but will be displayed as `null` in players search endpoint

**Comment by RealGatt** [comment]
So the player search page is a bit broken in my region currently... This seems like a borked migration on Blizzards' side (What's new though, am I right?)

<img width="1336" height="763" alt="Image" src="https://github.com/user-attachments/assets/7edc312c-0df7-4d0b-86bb-3580c1a2e4ea" />


I'll give the new release a run through, thankyou again @TeKrop!

**Comment by RealGatt** [comment]
Blizzard has updated the `/search/account-by-name/` in the region to be aligned with the rest of the world.

Regardless, thankyou for the effort in backdating support @TeKrop for the few weeks we needed it!!
